helm:
  versions: v3
git:
  pollInterval: 1m
  ssh:
    secretName: flux-git-deploy

chartsSyncInterval: 1m

logReleaseDiffs:
  true

configureRepositories:
  enable: true
  repositories:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
